_target_: src.models.detection.DetectionModel
_partial_: true

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.001
  amsgrad: false

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  eta_min: 0
  last_epoch: -1 
  verbose: false

trainable_backbone_layers: 5
compile: true
# min_size: 800
# max_size: 1333