defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - lr_monitor
  
model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  save_last: true
  auto_insert_metric_name: false

model_summary:
  max_depth: -1

