defaults:
  - test_cla

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      model.optimizer.lr: 0.001,0.0001
      trainer.max_epochs: 6,12
      resize_size: 224,320
      cl_method: cl,pl
      cl_score_method: self_confidence,normalized_margin